spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workly_bot
    username: postgres
    password: Saidkxon_2003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



bot:
  token: 8758105472:AAHa_dSEz_LBx5TZqpCVnT8S1Vb2pCT_R4s
  username: workly_attendance_bot

office:
  latitude: 41.360470
  longitude: 69.226713
  allowed-radius-meters: 50.0
  work-start-time: "09:00"
  work-end-time: "18:00"