spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telegrambot
    username: botuser
    password: Saidkxon_2003
  jpa:
    ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Tashkent



bot:
  token: 8758105472:AAHhL-LUXJajUrDM9Po0YY-LESCf4F_YjSU
  username: workly_attendance_bot

office:
  latitude: 41.360470
  longitude: 69.226713
  allowed-radius-meters: 50.0
  work-start-time: "09:00"
  work-end-time: "18:00"
app:
  time-zone: Asia/Tashkent
