package com.advancedprogramming.worklybot.bot.state;

public enum UserState {
    NONE,
    WAITING_FULL_NAME,
    WAITING_DEPARTMENT,
    WAITING_CORRECTION_DATE,
    WAITING_CORRECTION_TYPE,
    WAITING_CORRECTION_TIME,
    WAITING_ARRIVAL_LOCATION,
    WAITING_LEAVING_LOCATION,
    WAITING_EARLY_LEAVE_REASON,
    WAITING_HISTORY_MONTH,
    WAITING_MANAGER_HISTORY_MONTH
}
